apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "superset.fullname" . }}-assets
  labels:
    app: {{ include "superset.name" . }}
    chart: {{ include "superset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
binaryData:
  {{- $assetsLines := (splitList "\n" (trim (include "superset.nestedAssets" .))) }}
  {{- range $line := $assetsLines }}
    {{- $path := (index (splitList ":" $line) 0) }}
    {{- $data := (index (splitList ":" $line) 1) }}
  "{{ print ($path | replace "/" "..") }}": "{{ print $data }}"
  {{- end }}