apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superset.fullname" . }}
  labels:
    app: {{ include "superset.name" . }}
    chart: {{ include "superset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  init_superset.sh: {{ .Values.initFile | b64enc | quote }}
  init_superset_db.sh: {{ .Values.init.initFile | b64enc | quote }}
  superset_config.py: {{ .Values.configFile | b64enc | quote }}
  {{- range $key, $value := .Values.extraConfigFiles }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
stringData:
  {{- if .Values.configSecrets }}
  superset_config.yaml: |-
    {{- range $key, $val := .Values.configSecrets }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- else }}
  superset_config.yaml: "{}"
  {{- end }}

